apiVersion: apps/v1
kind: Deployment
metadata:
  name: scala-library
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scala-library
  template:
    metadata:
      labels:
        app: scala-library
    spec:
      containers:
      - name: scala-library
        image: scala-library-image
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: scala-library
spec:
  type: NodePort
  ports:
  - port: 8081
    nodePort: 30003
  selector:
    app: scala-library
